require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExLinksController do

  # This should return the minimal set of attributes required to create a valid
  # ExLink. As you add validations to ExLink, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      title: "VOCALENDAR",
      uri:  "http://vocalendar.jp/#{Time.now.to_f}",
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExLinksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ex_links as @ex_links" do
      ex_link = ExLink.create! valid_attributes
      get :index, params: {}, flash: valid_session
      expect(assigns(:ex_links)).to eq([ex_link])
    end
  end

  describe "GET show" do
    it "assigns the requested ex_link as @ex_link" do
      ex_link = ExLink.create! valid_attributes
      get :show, params: {:id => ex_link.to_param}, flash: valid_session
      expect(assigns(:ex_link)).to eq(ex_link)
    end
  end

  describe "GET new" do
    it "assigns a new ex_link as @ex_link" do
      get :new, params: {}, flash: valid_session
      expect(assigns(:ex_link)).to be_a_new(ExLink)
    end
  end

  describe "GET edit" do
    it "assigns the requested ex_link as @ex_link" do
      ex_link = ExLink.create! valid_attributes
      get :edit, params: {:id => ex_link.to_param}, flash: valid_session
      expect(assigns(:ex_link)).to eq(ex_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExLink" do
        expect {
          post :create, params: {:ex_link => valid_attributes}, flash: valid_session
        }.to change(ExLink, :count).by(1)
      end

      it "assigns a newly created ex_link as @ex_link" do
        post :create, params: {:ex_link => valid_attributes}, flash: valid_session
        expect(assigns(:ex_link)).to be_a(ExLink)
        expect(assigns(:ex_link)).to be_persisted
      end

      it "redirects to the created ex_link" do
        post :create, params: {:ex_link => valid_attributes}, flash: valid_session
        expect(response).to redirect_to(ExLink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ex_link as @ex_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(ExLink).to receive(:save).and_return(false)
        post :create, params: {:ex_link => { "uri" => "invalid value" }}, flash: valid_session
        expect(assigns(:ex_link)).to be_a_new(ExLink)
      end

      it "re-renders the 'new' template" do
        pending "do not works with responder"
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(ExLink).to receive(:save).and_return(false)
        post :create, params: {:ex_link => { "uri" => "invalid value" }}, flash: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ex_link" do
        ex_link = ExLink.create! valid_attributes
        # Assuming there are no other ex_links in the database, this
        # specifies that the ExLink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(ExLink).to receive(:update_attributes).with({ "title" => "VC" })
        put :update, params: {:id => ex_link.to_param, :ex_link => { "title" => "VC" }}, flash: valid_session
      end

      it "assigns the requested ex_link as @ex_link" do
        ex_link = ExLink.create! valid_attributes
        put :update, params: {:id => ex_link.to_param, :ex_link => { "title" => ex_link.title}}, flash: valid_session
        expect(assigns(:ex_link)).to eq(ex_link)
      end

      it "redirects to the ex_link" do
        ex_link = ExLink.create! valid_attributes
        put :update, params: {:id => ex_link.to_param, :ex_link => { "title" => ex_link.title}}, flash: valid_session
        expect(response).to redirect_to(ex_link)
      end
    end

  end

  describe "DELETE destroy" do
    it "destroys the requested ex_link" do
      ex_link = ExLink.create! valid_attributes
      expect {
        delete :destroy, params: {:id => ex_link.to_param}, flash: valid_session
      }.to change(ExLink, :count).by(-1)
    end

    it "redirects to the ex_links list" do
      ex_link = ExLink.create! valid_attributes
      delete :destroy, params: {:id => ex_link.to_param}, flash: valid_session
      expect(response).to redirect_to(ex_links_url)
    end
  end

  describe "GET redirect" do
    it "redirect there URI" do
      link = ExLink.create! valid_attributes
      get :redirect, params: {short_id: link.short_id}
      expect(response).to redirect_to(link.uri)
    end
  end
end
